#!/bin/bash

# Based in crypten - a script to encrypt files using openssl from GEN2LY

directorio=$2

function encriptar {
    FNAME=$1
    openssl des3 -salt -in "/tmp/$FNAME" -out "$directorio$FNAME.des3"
}

function desencriptar {
    FNAME=$1
    openssl des3 -d -salt -in "$directorio$FNAME" -out "/tmp/${FNAME%.[^.]*}"
}

function bitacora {

    file=$1
    filesave="/tmp/"$file

    if [[ !(-s "$directorio$file.des3") ]]; then
        echo "" > $filesave

        echo "Creando nueva bitacora..."
    else
        desencriptar $file".des3"
    fi
    
    cat $filesave

    echo ""
    echo -n "# Entrada: "
    read -e line

    echo $(date +"["%H:%M:%S"|"%D"]") $line >> $filesave

    encriptar $file
    rm $filesave
}

bitacora $1
